-- =========================================================================
-- Apartment Reviews — Token-Gated Comment System
-- =========================================================================
-- Only guests who received a "review invitation" email (after check-out)
-- can submit a review. Each invitation has a unique token used to authorize
-- one-time submission. Submissions land in 'pending' state and must be
-- approved by admin before they appear publicly.
-- =========================================================================

create table if not exists public.review_invitations (
  id uuid primary key default gen_random_uuid(),
  -- Token generated by the Edge Function (crypto.randomUUID + extra entropy).
  -- We keep DEFAULT here as a fallback for ad-hoc INSERTs.
  token text not null unique default (md5(random()::text || clock_timestamp()::text) || md5(random()::text || clock_timestamp()::text)),
  reservation_id uuid references public.reservations(id) on delete set null,
  property_id uuid not null references public.properties(id) on delete cascade,
  guest_email text not null,
  guest_name text,
  source_site text check (source_site in (
    'bodrumapartkiralama','bodrumapartvilla','bodruminsaatadilat','bodrumacilsu'
  )),
  language text default 'tr' check (language in ('tr','en','de','ru')),

  sent_at timestamptz default now(),
  expires_at timestamptz default (now() + interval '90 days'),
  used_at timestamptz,
  email_id text, -- Resend message id

  created_at timestamptz default now()
);

create index if not exists idx_ri_token       on public.review_invitations(token);
create index if not exists idx_ri_property    on public.review_invitations(property_id);
create index if not exists idx_ri_reservation on public.review_invitations(reservation_id);
create index if not exists idx_ri_used        on public.review_invitations(used_at);

-- ----------------------------------------------------------------------------
create table if not exists public.apartment_reviews (
  id uuid primary key default gen_random_uuid(),
  invitation_id uuid not null references public.review_invitations(id) on delete cascade,
  property_id uuid not null references public.properties(id) on delete cascade,

  rating int not null check (rating between 1 and 5),
  title text,
  body text not null check (char_length(body) between 10 and 2000),

  display_mode text not null default 'named' check (display_mode in ('named','anonymous')),
  display_name text,        -- nullable; if anonymous, shows "Anonim Misafir"
  language text default 'tr',
  source_site text,

  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  rejection_reason text,
  approved_by uuid,
  approved_at timestamptz,

  ip_address text,
  user_agent text,

  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  -- Each invitation can yield at most ONE review
  unique(invitation_id)
);

create index if not exists idx_ar_property on public.apartment_reviews(property_id);
create index if not exists idx_ar_status   on public.apartment_reviews(status);
create index if not exists idx_ar_approved on public.apartment_reviews(property_id, status) where status = 'approved';

drop trigger if exists trg_ar_updated_at on public.apartment_reviews;
create trigger trg_ar_updated_at
  before update on public.apartment_reviews
  for each row execute procedure public.set_updated_at();

-- ----------------------------------------------------------------------------
-- RLS
alter table public.review_invitations enable row level security;
alter table public.apartment_reviews  enable row level security;

-- Admin full access (matches existing auth.uid() pattern)
create policy "Auth full review_invitations" on public.review_invitations
  for all to public
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

create policy "Auth full apartment_reviews" on public.apartment_reviews
  for all to public
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

-- Public can READ approved reviews (for displaying on apartment pages)
create policy "Public read approved reviews" on public.apartment_reviews
  for select
  to anon
  using (status = 'approved');

-- Anonymous can submit reviews via the public Edge Function which uses
-- service role; no anon insert policy needed at the table level.

-- ----------------------------------------------------------------------------
-- Realtime
alter publication supabase_realtime add table public.review_invitations;
alter publication supabase_realtime add table public.apartment_reviews;

-- ----------------------------------------------------------------------------
-- Helper view: property review summary (avg rating + count of approved)
create or replace view public.property_review_summary as
  select
    property_id,
    count(*)::int as review_count,
    round(avg(rating)::numeric, 2) as average_rating,
    count(*) filter (where rating = 5)::int as count_5,
    count(*) filter (where rating = 4)::int as count_4,
    count(*) filter (where rating = 3)::int as count_3,
    count(*) filter (where rating = 2)::int as count_2,
    count(*) filter (where rating = 1)::int as count_1
  from public.apartment_reviews
  where status = 'approved'
  group by property_id;

grant select on public.property_review_summary to anon, authenticated;
